    
- name: software from native sources
  ansible.builtin.apt:
    update_cache: true
    install_recommends: true
    pkg:
    - playonlinux
    - bing
    - ceph-common
    - ceph-fuse
    - chromium-browser
    - cowsay
    - cryptsetup
    - curl
    - exfat-fuse
    - exfatprogs
    - expect
    - ghex
    - gnome-tweaks
    #- google-chrome-stable
    - gparted
    - grub-efi-amd64-bin
    - grub-efi-amd64-signed
    - htop
    - ipython3
    - language-pack-de-base
    - language-pack-de
    - language-pack-gnome-de-base
    - language-pack-gnome-de
    - language-pack-en-base
    - language-pack-en
    - language-pack-gnome-en-base
    - language-pack-gnome-en
    - language-selector-common
    - language-selector-gnome
    - libreoffice-help-de
    - libreoffice-l10n-de
    - libfuse2
    - libxml2-utils
    - ntfs-3g
    - okteta
    - openssh-client
    - openssh-server
    - python3
    - python3-pip
    - python3-venv
    - shim
    - shim-signed
    - ssh-import-id
    - sshpass
    - unison-gtk
    - unzip
    - vim
    - vlc
    - xfsprogs
  tags:
    - misc-from-native

- name: remove superfluous applications
  ansible.builtin.apt:
    pkg:
    - aisleriot
    - cheese
    #- gnome-keyring
    - gnome-mahjongg
    - gnome-mines
    - gnome-sudoku
    - imagemagick
    - transmission-common
    - transmission-gtk
    - usb-creator-common
    - usb-creator-gtk
    state: absent
    autoremove: true
  tags:
    - rm-apps

- name: upgrade system
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
    purge: yes
  tags:
    - upgrade

- name: disable gnome keyring
  ansible.builtin.command: rm /etc/xdg/autostart/gnome-keyring-*.desktop
  ignore_errors: true

- name: install common used multimedia packages excluding M$ ttf fonts
  ansible.builtin.command: apt install -y ubuntu-restricted-extras ttf-mscorefonts-installer-
  tags:
    - multimedia

- name: install M$ vscode
  ansible.builtin.import_tasks: vscode.yml
  tags:
    - microsoft-vscode

- name: install qgis
  ansible.builtin.import_tasks: qgis.yml
  tags:
    - qgis
