- name: install qgis
  block:
    - name: qgis - deploy ubuntugis ppa gpg key
      ansible.builtin.blockinfile:
        path: /etc/apt/trusted.gpg.d/ppa-ubuntugis.asc
        create: true
        block: |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          Comment: Hostname: 
          Version: Hockeypuck 2.1.0-223-gdc2762b

          xo0ESgc8TwEEANnh7UAVSnJoE8fyLMss5VUuG+1Bw5W2XWEyxuOCfMMAnJq4FY7Y
          OjaFwX37KdPTy5/+NVqegazUbB3WV8d21aRhN977HXYztt/1Ft73m30FLbZC3vRw
          aMg5oaWQ/XAy9ONY8QND/ahhSNf3d8wyrfAlG2RLaUeASDXqMBOU2fKVABEBAAHN
          GkxhdW5jaHBhZCB1YnVudHVnaXMtc3RhYmxlwrYEEwECACAFAkoHPE8CGwMGCwkI
          BwMCBBUCCAMEFgIDAQIeAQIXgAAKCRAInr4IMU3xYG3iA/0dnVOYqpLayEgzmlJ6
          mwJnVKcL+tGRfNsKQTHe77skFBcO/YyLez29HJJJS0xGtkZ+bUEQ3mdKnV/jGK4y
          geSouItfz3fM3/PvVbZMbARUTzOdIR/Hv8GUyVhY3dPR8NEyw0Op41kCOuxZBVU9
          85IQHDDQe6Fw1q6IFjOES0NMjQ==
          =ab3/
          -----END PGP PUBLIC KEY BLOCK-----
        mode: 644

    - name: Zeige den Versionsnamen (Codename)
      debug:
        msg: "{{ ansible_lsb.codename }}"

    - name: qgis - create ubuntugis ppa repository definition
      ansible.builtin.lineinfile:
        path: /etc/save/apt/sources.list.d/ppa-ubuntugis.list
        search_string: 'deb'
        line: 'deb https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu {{ ansible_lsb.codename }} main'
        create: true
      when: not nexus

    - name: qgis - create ubuntugis ppa repository definition
      ansible.builtin.lineinfile:
        path: /etc/save/apt/sources.list.d/ppa-ubuntugis.list
        search_string: 'deb'
        line: 'deb {{ nexus_proto }}://{{ nexus_name }}:{{ nexus_port }}/repository/ubuntu-{{ ansible_lsb.codename }}-ppa-ubuntugis {{ ansible_lsb.codename }} main'
        create: true
      when: nexus

    - name: qgis - install
      ansible.builtin.apt:
        update_cache: true
        install_recommends: true
        state: latest
        pkg:
          - qgis
          - qgis-plugin-grass

    - name: qgis - cleanup
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
  when: appadd_ppa_qgis

- name: qgis from native sources
  ansible.builtin.apt:
    update_cache: true
    install_recommends: true
    pkg:
    - qgias
  when: appadd_qgis